services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_safe_car
    env_file:
      - .env
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$SA_PASSWORD" -Q "SELECT 1" -C -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  initdb:
    build:
      context: ./init
    container_name: mssql_initdb
    env_file:
      - .env
    depends_on:
      mssql:
        condition: service_healthy
    volumes:
      - ./init/init-db.sh:/init-db.sh:ro
    entrypoint: ["/bin/bash", "/init-db.sh"]

  # server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: server_safe_car
  #   ports:
  #     - "8080:8080"
  #   env_file:
  #     - .env
  #   depends_on:
  #     mssql:
  #       condition: service_healthy
  #     initdb:
  #       condition: service_completed_successfully

volumes:
  mssql_data:
